# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
development:
  <<: *default
  username: development_nail_the_trail
  database: development_nail_the_trail
test:
  <<: *default
  database: test_nail_the_trail
production:
  <<: *default
  database: production_nail_the_trail
  username: production_nail_the_trail
